CODE_OF_CONDUCT.md
CONTRIBUTING.md
SECURITY.md

// Add a `#XXX` link to a related ticket

Add OSS bits

---

.github/workflows/e2e-onboarding-tests.yml
.github/workflows/e2e-popup-tests.yml
e2e/constants.ts
e2e/tests/common/connect-account.ts
e2e/tests/onboarding-flow/confirm-secret-phrase-flow.test.ts
e2e/tests/onboarding-flow/recover-secret-phrase-flow.test.ts
e2e/tests/popup/connect-account/connect-account-flow.test.ts
e2e/tests/popup/disconnect-account/disconnect-account-flow.test.ts
e2e/tests/popup/import-account-with-file-flow/import-account-with-file-flow.test.ts
e2e/tests/popup/signature-request-scenarios/signature-request-scenarios.test.ts
e2e/webdriver/driver.ts

- added signature request scenarios tests
- disabled Firefox CI tests
- fixed flaky onboarding test
- minor improvements 
#177

feature: add signature request scenarios tests

---

src/apps/popup/pages/account-list/index.tsx
src/apps/popup/pages/account-settings/content.tsx
src/apps/popup/pages/home/index.tsx
src/background/index.ts
src/background/service-message.ts
src/hooks/use-account-info/index.ts
src/hooks/use-account-info/use-account-info.ts
src/libs/services/account-info/account-info.ts
src/libs/services/account-info/constants.ts
src/libs/ui/components/avatar/avatar.tsx
src/libs/ui/components/typography/typography.tsx

- removed old implementation of account info standard support (home and account list pages)
- added AIS name on the account details page as an additional data row
#628

feature: add new account info standard support

---

src/apps/onboarding/pages/confirm-secret-phrase-success/content.tsx
src/apps/onboarding/pages/create-secret-phrase-confirmation/content.tsx
src/apps/popup/pages/backup-secret-phrase/content.tsx
src/libs/ui/components/underline/underline.tsx

- removed underline from the word `never`
#642

fix: remove underline from the word `never`

---

src/apps/popup/hooks/use-force-update.tsx
src/constants.ts
src/hooks/use-active-account-balance/use-active-account-balance.ts
src/libs/services/balance-service/balance-service.ts

Implemented an automatic periodical balance update service
https://make-software.atlassian.net/browse/WALLET-65

feature: implemented an automatic periodical balance update service

---

src/libs/ui/components/site-favicon-badge/site-favicon-badge.tsx

- link into one line always, and shows the full link on hover
[WALLET-66](https://make-software.atlassian.net/browse/WALLET-66)
[WALLET-66]: https://make-software.atlassian.net/browse/WALLET-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix website link display

---

src/apps/popup/pages/home/index.tsx
src/background/index.ts
src/libs/services/account-activity-service/account-activity-service.ts
src/libs/services/account-activity-service/constants.ts

- API for activity log of Casper integrated
- margin for the tabs container changed to prevent scroll when the tabs container has no content
[WALLET-61](https://make-software.atlassian.net/browse/WALLET-61)
[WALLET-61]: https://make-software.atlassian.net/browse/WALLET-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: integrate activity API

---

src/apps/popup/pages/transfer/amount-step.tsx
src/apps/popup/pages/transfer/content.tsx
src/apps/popup/pages/transfer/index.tsx
src/libs/ui/components/form-field/form-field.tsx
src/libs/ui/components/input/input.tsx

- added display fiat equivalent for transfer amount
[WALLET-83](https://make-software.atlassian.net/browse/WALLET-83)
[WALLET-83]: https://make-software.atlassian.net/browse/WALLET-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: add display fiat equivalent for transfer amount

---

src/apps/popup/pages/home/components/tokens-list/utils.ts
src/apps/popup/pages/token-details/content.tsx
src/apps/popup/pages/token-details/token.tsx
src/apps/popup/pages/transfer/index.tsx
src/constants.ts
src/libs/ui/components/activity-list/activity-list.tsx

Implemented erc20 token details page with token info
(https://make-software.atlassian.net/browse/WALLET-73)

Implemented erc20 token details page with token info

---

src/libs/layout/containers.ts
src/libs/layout/header/header-network-switcher.tsx
src/libs/ui/components/modal/modal.tsx
src/libs/ui/components/popover/popover.tsx
src/libs/ui/index.ts

- increased z index for modal and popover overlay
[WALLET-88](https://make-software.atlassian.net/browse/WALLET-88)
[WALLET-88]: https://make-software.atlassian.net/browse/WALLET-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix modal overlay

---

src/libs/ui/components/account-activity-plate/utils.ts

- fixed the case for the public key that we received from the API
[WALLET-96](https://make-software.atlassian.net/browse/WALLET-96)
[WALLET-96]: https://make-software.atlassian.net/browse/WALLET-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix 'Unknown' deploy is listed in activity log

---

src/apps/popup/pages/transfer/index.tsx
src/background/index.ts
src/background/redux/account-info/actions.ts
src/background/redux/account-info/reducer.ts
src/background/redux/account-info/selectors.ts
src/background/redux/account-info/types.ts
src/libs/services/account-activity-service/types.ts
src/libs/services/deployer-service/index.ts
src/libs/services/deployer-service/types.ts
src/libs/ui/components/account-activity-plate/account-activity-plate.tsx
src/libs/ui/components/account-activity-plate/utils.ts
src/libs/ui/components/activity-list/activity-list.tsx

based on #678 
- added pending state for transfers
[WALLET-68](https://make-software.atlassian.net/browse/WALLET-68)
[WALLET-68]: https://make-software.atlassian.net/browse/WALLET-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: add pending state for transfers

---

src/libs/ui/components/account-activity-plate/account-activity-plate.tsx

- changed font for the timestamp in the activity list
[WALLET-98](https://make-software.atlassian.net/browse/WALLET-98)
[WALLET-98]: https://make-software.atlassian.net/browse/WALLET-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: change font for timestamp

---

package-lock.json
package.json

- patched the webpack vulnerability
[WALLET-109](https://make-software.atlassian.net/browse/WALLET-109)
[WALLET-109]: https://make-software.atlassian.net/browse/WALLET-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: patch the webpack vulnerability

---

src/apps/popup/pages/transfer/amount-step.tsx
src/libs/ui/forms/form-validation-rules.ts

- fixed validation for amount and transfer id fields
[WALLET-108](https://make-software.atlassian.net/browse/WALLET-108)
[WALLET-108]: https://make-software.atlassian.net/browse/WALLET-108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix validation for amount and transfer id fields

---

src/apps/popup/app-router.tsx
src/libs/layout/locked-router/index.tsx

fixed cropped header background on the lock screen
[WALLET-107](https://make-software.atlassian.net/browse/WALLET-107)
[WALLET-107]: https://make-software.atlassian.net/browse/WALLET-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix cropped header background on lock screen

---

src/apps/popup/pages/transfer/amount-step.tsx
src/apps/popup/pages/transfer/confirm-step.tsx
src/apps/popup/pages/transfer/recipient-step.tsx
src/libs/layout/containers.ts
src/libs/ui/components/form-field/form-field.tsx

- changed indent for input container
[WALLET-111](https://make-software.atlassian.net/browse/WALLET-111)
[WALLET-111]: https://make-software.atlassian.net/browse/WALLET-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: add UI changes for transfer flow

---

src/apps/popup/pages/account-list/index.tsx
src/apps/popup/pages/account-settings/content.tsx
src/apps/popup/pages/activity-details/content.tsx
src/apps/popup/pages/home/index.tsx
src/apps/signature-request/pages/sign-deploy/deploy-value.tsx
src/libs/ui/components/account-activity-plate/account-activity-plate.tsx
src/libs/ui/components/active-account-plate/active-account-plate.tsx
src/libs/ui/components/deploy-status/deploy-status.tsx
src/libs/ui/components/hash/hash.tsx
src/libs/ui/components/hash/utils.ts
src/libs/ui/components/recipient-plate/recipient-plate.tsx
src/libs/ui/components/typography/typography.tsx

…tokens-list_**Make sure to fill in all the below sections.**_
- updated the hash component
[WALLET-99](https://make-software.atlassian.net/browse/WALLET-99)
[WALLET-99]: https://make-software.atlassian.net/browse/WALLET-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: update the hash component

---

src/hooks/use-account-pending-transactions/use-account-pending-transactions.ts
src/libs/ui/components/account-casper-activity-plate/account-casper-activity-plate.tsx
src/libs/ui/components/activity-list/activity-list.tsx
src/libs/ui/components/deploys-list/deploys-list.tsx

- removed pending transfers from casper token activity history
[WALLET-123](https://make-software.atlassian.net/browse/WALLET-123)
[WALLET-123]: https://make-software.atlassian.net/browse/WALLET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: remove pending transfers from casper token activity history

---

src/apps/popup/pages/receive/index.tsx

changed text for the button on receive token page
[WALLET-122](https://make-software.atlassian.net/browse/WALLET-122)
[WALLET-122]: https://make-software.atlassian.net/browse/WALLET-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: change text for the button on receive token page

---

src/libs/ui/components/token-plate/token-plate.tsx

fixed vertical alignment for ERC-20 tokens
[WALLET-125](https://make-software.atlassian.net/browse/WALLET-125)
[WALLET-125]: https://make-software.atlassian.net/browse/WALLET-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix vertical alignment for ERC-20 tokens

---

src/apps/popup/pages/transfer/success-step.tsx

- changed text for the submitted transfer on the confirmation screen
[WALLET-119](https://make-software.atlassian.net/browse/WALLET-119)
[WALLET-119]: https://make-software.atlassian.net/browse/WALLET-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: change submission confirmation text 

---

src/apps/popup/index.html
src/apps/popup/pages/home/components/tokens-list/utils.ts
src/hooks/use-casper-token/use-casper-token.ts
src/libs/services/erc20-service/types.ts
src/manifest.v2.json
src/manifest.v3.json

- added icons for erc-20 tokens
[WALLET-126](https://make-software.atlassian.net/browse/WALLET-126)
[WALLET-126]: https://make-software.atlassian.net/browse/WALLET-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: add ERC-20 token icon in Casper Wallet

---

src/apps/connect-to-app/index.tsx
src/apps/import-account-with-file/app-router.tsx
src/apps/import-account-with-file/index.tsx
src/apps/popup/index.tsx
src/apps/signature-request/index.tsx
src/libs/layout/layout-window.tsx
src/libs/layout/popup-layout.tsx

- fixed scrollbar styling
[WALLET-94](https://make-software.atlassian.net/browse/WALLET-94)
[WALLET-94]: https://make-software.atlassian.net/browse/WALLET-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix scrollbar styling

---

src/apps/popup/pages/activity-details/content.tsx
src/apps/popup/pages/home/index.tsx
src/apps/popup/pages/transfer/index.tsx
src/constants.ts
src/libs/ui/components/account-activity-plate/account-activity-plate.tsx
src/libs/ui/components/account-casper-activity-plate/account-casper-activity-plate.tsx
src/libs/ui/components/tabs/tabs.tsx

- added error handle for invalid number issues
- fixed possible issues with the recipient public key on the activity details page
- minor improvements
[WALLET-120](https://make-software.atlassian.net/browse/WALLET-120)
[WALLET-120]: https://make-software.atlassian.net/browse/WALLET-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix invalid number error in deploys tab

---

src/libs/ui/components/account-activity-plate/account-activity-plate.tsx
src/libs/ui/utils/utils.ts

- fixed issues when some data doesn't provide
[WALLET-138](https://make-software.atlassian.net/browse/WALLET-138)
[WALLET-138]: https://make-software.atlassian.net/browse/WALLET-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix page crash when some data doesn't provide

---

src/apps/popup/pages/transfer/confirm-step.tsx

- changed header name for transfer confirm step
[WALLET-137](https://make-software.atlassian.net/browse/WALLET-137)
[WALLET-137]: https://make-software.atlassian.net/browse/WALLET-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix header name for transfer confirm step

---

src/apps/popup/pages/receive/content.tsx

- fixed size for QR code
[WALLET-136](https://make-software.atlassian.net/browse/WALLET-136)
[WALLET-136]: https://make-software.atlassian.net/browse/WALLET-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix size for QR code

---

src/apps/popup/pages/home/index.tsx
src/constants.ts

Topper production configuration
// Add a `#XXX` link to a related ticket

Configure prod Topper integration

---

.github/pull_request_template.md

- pull request template file was updated
// Add a `#XXX` link to a related ticket

update pull request template file

---

src/apps/popup/pages/activity-details/content.tsx
src/apps/popup/pages/activity-details/index.tsx
src/apps/popup/pages/token-details/index.tsx
src/libs/layout/header/header-view-in-explorer.tsx

- moved cspr link button to the navigation bar
[WALLET-144](https://make-software.atlassian.net/browse/WALLET-144)
[WALLET-144]: https://make-software.atlassian.net/browse/WALLET-144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: move cspr link button to the navigation bar

---

src/apps/popup/pages/activity-details/content.tsx
src/libs/services/account-activity-service/types.ts
src/libs/ui/components/account-activity-plate/account-activity-plate.tsx
src/libs/ui/components/account-casper-activity-plate/account-casper-activity-plate.tsx
src/libs/ui/components/avatar/avatar.tsx
src/libs/ui/utils/utils.ts

- fixed the issue of not showing the recipient address for the delegation/redelegation/undelegation deploys
[WALLET-145](https://make-software.atlassian.net/browse/WALLET-145)
[WALLET-145]: https://make-software.atlassian.net/browse/WALLET-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix issue with not showing recipient address

---

src/libs/ui/components/deploy-status/deploy-status.tsx

- removed the success label from the activity list
[WALLET-97](https://make-software.atlassian.net/browse/WALLET-97)
[WALLET-97]: https://make-software.atlassian.net/browse/WALLET-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove the success label from the activity list

---

README.md

We now provide Casper Wallet integration through CSPR.click. So let's make it known properly.
// Add a `#XXX` link to a related ticket

Update README.md to add reference to CSPR.click for integration
